### ISSUE TITLE
Plan 9

### ISSUE THREAD

**Issue by LizzyFleckenstein03** [rice7th/swef#1]
This does not work on Plan 9

**Comment by JhonnyRice** [comment]
wow wtf

**Comment by JhonnyRice** [comment]
if you instead mean Plan9 The OS then im working on it

**Comment by rice7th** [comment]
if you find a way to tell the program that the current os is Plan9 like `uname` please tell me. As i've just discovered plan9 is very hard to implement. Not even neofetch can run on it. BUT i don't think that it is impossible to implement. If you find anything helpful please tell me!

**Comment by rice7th** [comment]
OK! After 19 days of waiting, it should work on plan9 now!

**Comment by rice7th** [comment]
I tested, at leas on my VM it works
