### ISSUE TITLE
NetBSD at freeshell.org

### ISSUE THREAD

**Issue by polluks** [rice7th/swef#3]
```
$ ./swef
lua: ./swef:364: attempt to index a nil value (local 'osname')
stack traceback:
        ./swef:364: in local 'ascii'
        ./swef:609: in main chunk
        [C]: in ?
```
```
$ lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
```

**Comment by rice7th** [comment]
1. what is freeshell.org
2. thats kinda weird. In my NetBSD install it worked. Ill try to figure it out a bit better.

**Comment by polluks** [comment]
freeshell.org is a well-known host, therefore I'm not root.
NetBSD sdf 8.2 NetBSD 8.2 (GENERIC) #0: Tue Mar 31 05:08:40 UTC 2020  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64

**Comment by rice7th** [comment]
Apparently it fails to get the osname. The only way it does that is via the `uname`  command. Test if `uname -s` works

**Comment by polluks** [comment]
indeed
```
$ uname      
NetBSD
$ uname -s
NetBSD
$ uname -o
uname: unknown option -- o
usage: uname [-amnprsv]
$ uname -o -s
uname: unknown option -- o
usage: uname [-amnprsv]
$ uname -s -o
uname: unknown option -- o
usage: uname [-amnprsv]

**Comment by rice7th** [comment]
oh, the ```-o``` option fails. Interesting

**Comment by rice7th** [comment]
okay no i am stupid and declared ```osname``` on another scope lmao

now it is fixed

**Comment by polluks** [comment]
It's getting better
```
$ ./swef
lua: ./swef:595: attempt to concatenate a nil value (field 'yellow')
stack traceback:
        ./swef:595: in local 'ascii'
        ./swef:658: in main chunk
        [C]: in ?

**Comment by rice7th** [comment]
What is that?

**Comment by rice7th** [comment]
bruh i typed yellow in lowerfase instead the variable name is uppercase...


Try now i guess?

**Comment by polluks** [comment]
works, thx!
```
\--___   _. os: NetBSD
 \  __'"'_/ wm: tty
  \"  '"'   kn: NetBSD 8.2
   \        sh: bash
