### ISSUE TITLE
Plan 9 at freeshell.org

### ISSUE THREAD

**Issue by polluks** [rice7th/swef#4]
```
cpu% lu9 swef
/rc/lib/rcmain:24 *eval*:1: uname: './uname' not found
/rc/lib/rcmain:24 *eval*:1: uname: './uname' not found
lu9: swef:269: attempt to index a nil value (global 'kern')
stack traceback:
	swef:269: in local 'fetch'
	swef:605: in main chunk
	[C]: in ?
```
```
cpu% lu9 -v
5.4
cpu% ls -l /bin/ape/uname
--rwxrwxr-x M 67049 sys sys 161682 Jun 11 20:00 /bin/ape/uname
```

**Comment by rice7th** [comment]
temporary move /bin/ape/uname to the current swef location

**Comment by polluks** [comment]
Well, the error disappears but plan_nine_exists fails.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4707573/174287321-8de96e5b-1f02-40d5-931f-209877da252b.png">
How about this? https://stackoverflow.com/a/4991602/1430535

**Comment by rice7th** [comment]
Seems interesting. I will look into that.

**Comment by rice7th** [comment]
I may have fixed it but i dont have a Plan9 VM/machine to test that so please try again and tell me if it fails

**Comment by rice7th** [comment]
So is it working?

**Comment by polluks** [comment]
yep
<img width="145" alt="1 3" src="https://user-images.githubusercontent.com/4707573/184455366-d9aa7f67-58ff-4447-948a-a9c287be6fac.png">

**Comment by rice7th** [comment]
cool

**Comment by polluks2** [comment]
The kernel info looks redundant, how about something like `uname -r`?

**Comment by polluks** [comment]
The kernel info looks redundant, how about something like `uname -r`?

**Comment by polluks** [comment]
FYI https://github.com/arwn/gfetch
