### ISSUE TITLE
Wrong shell

### ISSUE THREAD

**Issue by polluks** [rice7th/swef#6]
macOS uses zsh
```
  __()_         os: Mac Os
.'     '.       wm: Quartz Compositor
|      (        kn: Darwin 21.5.0
'._____.'       sh: sh
```
```zsh
$ echo $SHELL
/bin/zsh
```

**Comment by rice7th** [comment]
This is a common bug caused by the $SHELL variable. I will look forward and fix that.

**Comment by rice7th** [comment]
should be fixed now

**Comment by rice7th** [comment]
Okay, so, the bug was the fact that in swef, if the basename program is not found, then it will fallback to ```sh```. Now if there is no basename, it will just display $SHELL. This means that you will get ```/bin/zsh``` instead of ```zsh```

**Comment by polluks2** [comment]
thx!
